### PR TITLE
Update redis binaries

### PR DESCRIPTION
**Pull request by martin-mfg**
**This PR includes up-to-date redis binaries. It also adds support for Mac OS on ARM. And it drops support for Mac OS on x86 and Windows on x86.** Because I couldn't find any up-to-date binaries for Windows/Mac OS x86. But I can re-add the old 2.8.19 binaries for this if you want.

I tested the changes on several platforms to ensure the new binaries work as expected. Test results can be found [here](https://github.com/martin-mfg/embedded-redis/actions/runs/4445113942). As Mac OS on ARM isn't supported by Github actions, I tested it on codemagic.io:
grafik

### CODE REVIEW

**Comment by codemonstur** [comment]
I downloaded all the files from the original sources and checked them against the versions in the pull-request (not that I don't trust you or anything :))

```
$ sha256sum redis-server-6.2.7-linux-386
7439d339751e396cef7205a3169c96f1c53661f65d473b8d086e2d1826f48145  redis-server-6.2.7-linux-386
$ sha256sum ../plr_source/redis-server-6.2.7-linux-386
7439d339751e396cef7205a3169c96f1c53661f65d473b8d086e2d1826f48145  ../plr_source/redis-server-6.2.7-linux-386

$ sha256sum redis-server-6.2.7-linux-arm64
036a23aa65bfb31d2a048aa96c170b38c2fbd4f1de68ef0f9c3133dd4b1474cd  redis-server-6.2.7-linux-arm64
$ sha256sum ../plr_source/redis-server-6.2.7-linux-arm64
036a23aa65bfb31d2a048aa96c170b38c2fbd4f1de68ef0f9c3133dd4b1474cd  ../plr_source/redis-server-6.2.7-linux-arm64

$ unzip -j redis-stack-server-6.2.6-v5.catalina.x86_64.zip "bin/redis-server" -d .
$ mv redis-server redis-6.2.6-v5.catalina.x86_64
$ sha256sum redis-6.2.6-v5.catalina.x86_64
7a4eb450d90a6ce9a2c651cfc4a0613b980a270c6426cbb6fa42d6c3beec9ce8  redis-6.2.6-v5.catalina.x86_64
$ sha256sum ../plr_source/redis-server-6.2.6-v5-darwin-amd64
7a4eb450d90a6ce9a2c651cfc4a0613b980a270c6426cbb6fa42d6c3beec9ce8  ../plr_source/redis-server-6.2.6-v5-darwin-amd64

$ tar -zxvf redis-stack-server-6.2.6-v5.jammy.x86_64.tar.gz ./redis-stack-server-6.2.6-v5/bin/redis-server
$ sha256sum redis-stack-server-6.2.6-v5/bin/redis-server
1f716094e08a25faee2bc7626feb9e13464ed89018ac5c376c5e9cff06bdcf52  redis-stack-server-6.2.6-v5/bin/redis-server
$ sha256sum ../plr_source/redis-server-6.2.6-v5-linux-amd64
1f716094e08a25faee2bc7626feb9e13464ed89018ac5c376c5e9cff06bdcf52  ../plr_source/redis-server-6.2.6-v5-linux-amd64

$ unzip -j redis-stack-server-6.2.6-v5.monterey.arm64.zip "bin/redis-server" -d .
$ mv redis-server redis-server-6.2.6-v5.monterey.arm64
$ sha256sum redis-server-6.2.6-v5.monterey.arm64
c523aec5a9b6f565cff0271ef67f5c51fa83e1180e3e954ab5251b3cf6282b76  redis-server-6.2.6-v5.monterey.arm64
$ sha256sum ../plr_source/redis-server-6.2.6-v5-darwin-arm64
c523aec5a9b6f565cff0271ef67f5c51fa83e1180e3e954ab5251b3cf6282b76  ../plr_source/redis-server-6.2.6-v5-darwin-arm64

$ unzip -j Redis-x64-5.0.14.1.zip "redis-server.exe" -d .
$ mv redis-server.exe redis-x64-5.0.14.exe
$ sha256sum redis-x64-5.0.14.exe
79cd623a9999d75e944e8d2509547ddeee67a2c6c7b88d11d1137eb57fec10a0  redis-x64-5.0.14.exe
$ sha256sum ../plr_source/redis-server-5.0.14.1-windows-amd64.exe
79cd623a9999d75e944e8d2509547ddeee67a2c6c7b88d11d1137eb57fec10a0  ../plr_source/redis-server-5.0.14.1-windows-amd64.exe
```

**Comment by codemonstur** [comment]
And then I ran virus scans against them all with virustotal. Results [here](https://github.com/codemonstur/embedded-redis/tree/master/src/docs/virusscans). Only windows binary shows 1 scanner complaining. I think thats a false positive.

**Comment by codemonstur** [comment]
Thanks!

**Comment by martin-mfg** [comment]
> Google says Microsoft stopped supporting 32bit on May 13, 2020. Not extremely long ago but 32bit still feels ancient to me. Whats your opinion on leaving 2.8.19 in for 32bit x86 windows only?

Hard to decide. But I'd probably not add the old binary. It looks like it's a [security risk](https://www.cvedetails.com/vulnerability-list/vendor_id-18560/product_id-47087/Redislabs-Redis.html). And it should not be required by most users. And those who need it can still provide their own binary.

> I downloaded all the files from the original sources and checked them against the versions in the pull-request (not that I don't trust you or anything :))

Good to see maintainers aware of security implications and double-checking things. :)

**Comment by codemonstur** [comment]
I [ran dependency check](https://github.com/codemonstur/embedded-redis/issues/14) and it also reports CVEs for the current version. But it's still better than 2.8.19. I'm going to leave it out.

**Pull request merged**
